version: 1
module_version: 0.1.7

test_defaults:
  after_init: ["ls -la ../../"]

tests:
  - name: Default pet test
    project_root: examples/default
  - name: Failing pet test
    project_root: examples/failing
    negative: true
